# These keys from from the source of BodegaBot
# https://cheapbotsdonequick.com/source/BodegaBot
# "employees": ["employees","founders","designers","programmers","engineers","product managers","interns"],
#
# NOTE: If you're adding somebody other than yourself, make sure you have their permission!
#
"employees":
  - chiangku
  - jeeyoungk
  - sentiental
  - tuanycakes
"founders":
"designers":
"programmers":
  - chiangku
  - jeeyoungk
  - sentiental
"engineers":
  - chiangku
  - jeeyoungk
  - sentiental
  - tuanycakes
"product managers":
"interns":
